#!/bin/bash
### BEGIN INIT INFO
# Provides:          solrIndexer
# Required-Start:    tomcat7
# Required-Stop:     tomcat7
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: solrIndexer
# Description:       Apache Solr Indexer Init Skript - This file should be used to construct scripts to be
#                    placed in /etc/init.d.
### END INIT INFO

### 
#
# Goobi viewer - Indexer
#
# Author: intranda GmbH <support@intranda.com>
#
###

#set -x
set -e
set -u
set -o pipefail

# Die folgenden Punkte ggfs. anpassen
INDEXERPATH=/opt/digiverso/indexer
DAEMON=$INDEXERPATH/solrIndexer.jar
CONFIGFILE="$INDEXERPATH/solr_indexerconfig.xml"

SHUTDOWNFILE=/opt/digiverso/viewer/hotfolder/.SHUTDOWN_INDEXER
LOGFILE=/opt/digiverso/logs/indexer.log
LOGCONFIG=/opt/digiverso/indexer/indexerlog4j.properties
RUNNINGUSER=tomcat7

PATH=/sbin:/usr/sbin:/bin:/usr/bin
DESC="Goobi viewer - Indexer"
SOLRURL="http://localhost:8080/solr/"
SOLRRESULT="HTTP/1.1 200 OK"


### Unbekannte Fehler
trap "echo Uhandled error." ERR

### is the Indexer running?
is_indexer_running() {
    PID=$(pgrep -f "java -jar .*$DAEMON"  ) || PID=''
    if [ -n "$PID" ] ; then
	return 0
    else
	return 1
    fi
}

### is Apache Solr running?
is_solr_running() {
    echo -n "Check for solrApp"
    for wait in {1..60} ; do
        wget -S -O - "$SOLRURL" 2>&1 | grep &>/dev/null "$SOLRRESULT" && break
        echo -n "."
        sleep 1
    done
    if wget -S -O - "$SOLRURL" 2>&1  | grep &>/dev/null "$SOLRRESULT" ; then
	echo "...OK"
	return 0
    else
	echo "...FAILED"
	echo "Please check whether solr is running!"
	return 1
    fi
}

indexer_shutdown() {
    echo -n "Shutting down $DESC."
    touch $SHUTDOWNFILE
    for wait in {1..30} ; do
	echo -n "."
	sleep 1
	is_indexer_running || break
    done
    if is_indexer_running ; then
	echo "... failed to shutdown Indexer, still running with pid: $PID"
	return 1
    else
	echo "... Indexer shut down successfully."
	return 0
    fi
}

indexer_start() {
    if is_solr_running ; then	    
	su $RUNNINGUSER -- -c "java -jar -Dlog4j.configuration=file://$LOGCONFIG $DAEMON $CONFIGFILE 1> /dev/null 2>> $LOGFILE &"
	sleep 1
	if is_indexer_running ; then
	    echo $DESC started with pid: $PID
	    return 0
	else
	    echo $DESC start failed!
	    return 1
        fi
    else
        return 1
    fi
}

cd $INDEXERPATH

case "${1:-}" in
  start)
	if is_indexer_running ; then
	    echo "Already running with pid: $PID"  	
	else
	    indexer_start || exit 7
	fi
	;;

  stop)
  	if is_indexer_running ; then
            indexer_shutdown || exit 1
	else
            echo "$DESC is not running." 
        fi
	;;

  status)
  	if is_indexer_running ; then
	    echo "Still running with pid: $PID"
	else
	    echo "$DESC is not running."
	    exit 3
	fi
	;;

  restart|force-reload)
        echo "Restarting $DESC"
	if is_indexer_running ; then
	    indexer_shutdown || exit 1
	fi
	indexer_start || exit 7
	;;

  *)
	echo "Usage: $0 {start|stop|status|restart|force-reload}" >&2
	exit 3
	;;
esac

exit 0

