name: Standard CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
      name: Checkout Goobi viewer Indexer

    - uses: actions/cache@v1
      name: Caching
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Set up Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Compile Goobi viewer Indexer
      run: mvn -f goobi-viewer-indexer/pom.xml clean package -U -B

