name: Standard CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
      name: Checkout Goobi viewer Indexer

    - uses: actions/cache@v1
      name: Caching
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Compile Goobi viewer Indexer
      run: mvn -f goobi-viewer-indexer/pom.xml clean package -U -B

